import { apiCreatePatient, apiCreateTest, apiGetAllPatients } from "./backend";
import type { LabTest, Patient } from "./types";
import { nowISO } from "./utils";

const now = nowISO();

const SEED_TESTS: LabTest[] = [
  {
    id: "test-cbc",
    name: "CBC (Complete Blood Count)",
    category: "Hematology",
    price: 350,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-cbc-1",
        name: "Hemoglobin",
        unit: "g/dL",
        referenceRange: "12.0-17.5",
        referenceMin: 12,
        referenceMax: 17.5,
      },
      {
        id: "p-cbc-2",
        name: "WBC Count",
        unit: "10³/µL",
        referenceRange: "4.5-11.0",
        referenceMin: 4.5,
        referenceMax: 11,
      },
      {
        id: "p-cbc-3",
        name: "Platelets",
        unit: "10³/µL",
        referenceRange: "150-400",
        referenceMin: 150,
        referenceMax: 400,
      },
      {
        id: "p-cbc-4",
        name: "RBC Count",
        unit: "10⁶/µL",
        referenceRange: "4.2-5.4",
        referenceMin: 4.2,
        referenceMax: 5.4,
      },
      {
        id: "p-cbc-5",
        name: "Hematocrit (PCV)",
        unit: "%",
        referenceRange: "36-52",
        referenceMin: 36,
        referenceMax: 52,
      },
      {
        id: "p-cbc-6",
        name: "MCV",
        unit: "fL",
        referenceRange: "80-100",
        referenceMin: 80,
        referenceMax: 100,
      },
      {
        id: "p-cbc-7",
        name: "MCH",
        unit: "pg",
        referenceRange: "27-33",
        referenceMin: 27,
        referenceMax: 33,
      },
      {
        id: "p-cbc-8",
        name: "MCHC",
        unit: "g/dL",
        referenceRange: "32-36",
        referenceMin: 32,
        referenceMax: 36,
      },
    ],
  },
  {
    id: "test-lft",
    name: "Liver Function Test (LFT)",
    category: "Biochemistry",
    price: 900,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-lft-1",
        name: "Total Bilirubin",
        unit: "mg/dL",
        referenceRange: "0.2-1.2",
        referenceMin: 0.2,
        referenceMax: 1.2,
      },
      {
        id: "p-lft-2",
        name: "SGOT (AST)",
        unit: "U/L",
        referenceRange: "10-40",
        referenceMin: 10,
        referenceMax: 40,
      },
      {
        id: "p-lft-3",
        name: "SGPT (ALT)",
        unit: "U/L",
        referenceRange: "7-56",
        referenceMin: 7,
        referenceMax: 56,
      },
      {
        id: "p-lft-4",
        name: "Alkaline Phosphatase",
        unit: "U/L",
        referenceRange: "44-147",
        referenceMin: 44,
        referenceMax: 147,
      },
      {
        id: "p-lft-5",
        name: "Total Protein",
        unit: "g/dL",
        referenceRange: "6.0-8.3",
        referenceMin: 6,
        referenceMax: 8.3,
      },
    ],
  },
  {
    id: "test-kft",
    name: "Kidney Function Test (KFT)",
    category: "Biochemistry",
    price: 800,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-kft-1",
        name: "Blood Urea",
        unit: "mg/dL",
        referenceRange: "15-45",
        referenceMin: 15,
        referenceMax: 45,
      },
      {
        id: "p-kft-2",
        name: "Serum Creatinine",
        unit: "mg/dL",
        referenceRange: "0.6-1.2",
        referenceMin: 0.6,
        referenceMax: 1.2,
      },
      {
        id: "p-kft-3",
        name: "Uric Acid",
        unit: "mg/dL",
        referenceRange: "3.5-7.2",
        referenceMin: 3.5,
        referenceMax: 7.2,
      },
      {
        id: "p-kft-4",
        name: "eGFR",
        unit: "mL/min/1.73m²",
        referenceRange: ">60",
        referenceMin: 60,
      },
    ],
  },
  {
    id: "test-tft",
    name: "Thyroid Function Test (TFT)",
    category: "Endocrinology",
    price: 1100,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-tft-1",
        name: "TSH",
        unit: "µIU/mL",
        referenceRange: "0.4-4.0",
        referenceMin: 0.4,
        referenceMax: 4,
      },
      {
        id: "p-tft-2",
        name: "T3 (Total)",
        unit: "ng/dL",
        referenceRange: "80-200",
        referenceMin: 80,
        referenceMax: 200,
      },
      {
        id: "p-tft-3",
        name: "T4 (Total)",
        unit: "µg/dL",
        referenceRange: "5.0-12.0",
        referenceMin: 5,
        referenceMax: 12,
      },
    ],
  },
  {
    id: "test-lipid",
    name: "Lipid Profile",
    category: "Biochemistry",
    price: 750,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-lip-1",
        name: "Total Cholesterol",
        unit: "mg/dL",
        referenceRange: "<200",
        referenceMax: 200,
      },
      {
        id: "p-lip-2",
        name: "HDL Cholesterol",
        unit: "mg/dL",
        referenceRange: ">40",
        referenceMin: 40,
      },
      {
        id: "p-lip-3",
        name: "LDL Cholesterol",
        unit: "mg/dL",
        referenceRange: "<100",
        referenceMax: 100,
      },
      {
        id: "p-lip-4",
        name: "Triglycerides",
        unit: "mg/dL",
        referenceRange: "<150",
        referenceMax: 150,
      },
    ],
  },
  {
    id: "test-hba1c",
    name: "HbA1c (Glycated Haemoglobin)",
    category: "Biochemistry",
    price: 650,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-hba-1",
        name: "HbA1c",
        unit: "%",
        referenceRange: "<5.7",
        referenceMax: 5.7,
      },
    ],
  },
  {
    id: "test-dengue",
    name: "Dengue NS1 Antigen + IgM/IgG",
    category: "Serology",
    price: 900,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-den-1",
        name: "NS1 Antigen",
        unit: "",
        referenceRange: "Negative",
      },
      {
        id: "p-den-2",
        name: "IgM Antibody",
        unit: "",
        referenceRange: "Negative",
      },
      {
        id: "p-den-3",
        name: "IgG Antibody",
        unit: "",
        referenceRange: "Negative",
      },
    ],
  },
  {
    id: "test-malaria",
    name: "Malaria Antigen Test",
    category: "Serology",
    price: 400,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-mal-1",
        name: "P. falciparum Antigen",
        unit: "",
        referenceRange: "Negative",
      },
      {
        id: "p-mal-2",
        name: "P. vivax Antigen",
        unit: "",
        referenceRange: "Negative",
      },
    ],
  },
  {
    id: "test-widal",
    name: "Widal Test",
    category: "Serology",
    price: 250,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-wid-1",
        name: "S. Typhi O",
        unit: "titre",
        referenceRange: "<1:80",
      },
      {
        id: "p-wid-2",
        name: "S. Typhi H",
        unit: "titre",
        referenceRange: "<1:80",
      },
      {
        id: "p-wid-3",
        name: "S. Paratyphi AO",
        unit: "titre",
        referenceRange: "<1:80",
      },
      {
        id: "p-wid-4",
        name: "S. Paratyphi BH",
        unit: "titre",
        referenceRange: "<1:80",
      },
    ],
  },
  {
    id: "test-vitd",
    name: "Vitamin D (25-OH)",
    category: "Biochemistry",
    price: 1400,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-vitd-1",
        name: "25-OH Vitamin D",
        unit: "ng/mL",
        referenceRange: "30-100",
        referenceMin: 30,
        referenceMax: 100,
      },
    ],
  },
  {
    id: "test-vitb12",
    name: "Vitamin B12",
    category: "Biochemistry",
    price: 1200,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-vitb-1",
        name: "Vitamin B12",
        unit: "pg/mL",
        referenceRange: "200-900",
        referenceMin: 200,
        referenceMax: 900,
      },
    ],
  },
  {
    id: "test-rbs",
    name: "Random Blood Sugar (RBS)",
    category: "Biochemistry",
    price: 80,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-rbs-1",
        name: "Random Blood Glucose",
        unit: "mg/dL",
        referenceRange: "70-140",
        referenceMin: 70,
        referenceMax: 140,
      },
    ],
  },
  {
    id: "test-urine",
    name: "Urine Routine & Microscopy",
    category: "Pathology",
    price: 200,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-uri-1",
        name: "Colour",
        unit: "",
        referenceRange: "Pale Yellow",
      },
      {
        id: "p-uri-2",
        name: "pH",
        unit: "",
        referenceRange: "4.5-8.0",
        referenceMin: 4.5,
        referenceMax: 8.0,
      },
      { id: "p-uri-3", name: "Protein", unit: "", referenceRange: "Negative" },
      {
        id: "p-uri-4",
        name: "Pus Cells",
        unit: "/HPF",
        referenceRange: "0-5",
        referenceMin: 0,
        referenceMax: 5,
      },
    ],
  },
  {
    id: "test-esr",
    name: "ESR (Erythrocyte Sedimentation Rate)",
    category: "Hematology",
    price: 100,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-esr-1",
        name: "ESR",
        unit: "mm/hr",
        referenceRange: "0-20",
        referenceMin: 0,
        referenceMax: 20,
      },
    ],
  },
  {
    id: "test-crp",
    name: "C-Reactive Protein (CRP)",
    category: "Immunology",
    price: 450,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-crp-1",
        name: "CRP",
        unit: "mg/L",
        referenceRange: "<5",
        referenceMax: 5,
      },
    ],
  },
  {
    id: "test-uricacid",
    name: "Serum Uric Acid",
    category: "Biochemistry",
    price: 180,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-ua-1",
        name: "Uric Acid",
        unit: "mg/dL",
        referenceRange: "3.5-7.2",
        referenceMin: 3.5,
        referenceMax: 7.2,
      },
    ],
  },
  {
    id: "test-thyroid3",
    name: "Thyroid Panel (TSH + T3 + T4)",
    category: "Endocrinology",
    price: 1500,
    createdAt: now,
    updatedAt: now,
    parameters: [
      {
        id: "p-tp-1",
        name: "TSH",
        unit: "µIU/mL",
        referenceRange: "0.4-4.0",
        referenceMin: 0.4,
        referenceMax: 4,
      },
      {
        id: "p-tp-2",
        name: "Free T3",
        unit: "pg/mL",
        referenceRange: "2.3-4.2",
        referenceMin: 2.3,
        referenceMax: 4.2,
      },
      {
        id: "p-tp-3",
        name: "Free T4",
        unit: "ng/dL",
        referenceRange: "0.89-1.76",
        referenceMin: 0.89,
        referenceMax: 1.76,
      },
    ],
  },
];

const SEED_PATIENTS: Patient[] = [
  {
    id: "pat-001",
    name: "Rajesh Kumar",
    age: 45,
    gender: "Male",
    phone: "9876543210",
    address: "12, MG Road, Bangalore",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pat-002",
    name: "Priya Sharma",
    age: 32,
    gender: "Female",
    phone: "9845012345",
    address: "45, Koramangala, Bangalore",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pat-003",
    name: "Mohammed Farooq",
    age: 58,
    gender: "Male",
    phone: "9900123456",
    address: "7, Shivaji Nagar, Pune",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pat-004",
    name: "Sunita Reddy",
    age: 27,
    gender: "Female",
    phone: "9712345678",
    address: "22, Banjara Hills, Hyderabad",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "pat-005",
    name: "Amit Patel",
    age: 41,
    gender: "Male",
    phone: "9601234567",
    address: "3, Satellite Road, Ahmedabad",
    createdAt: now,
    updatedAt: now,
  },
];

export async function seedDefaultData(): Promise<void> {
  try {
    const existing = await apiGetAllPatients();
    if (existing.length > 0) return;
    await Promise.all(SEED_TESTS.map((t) => apiCreateTest(t)));
    await Promise.all(SEED_PATIENTS.map((p) => apiCreatePatient(p)));
    console.log("[PathLab] Seeded default data");
  } catch (e) {
    console.warn("[PathLab] Seed failed", e);
  }
}
