/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'status' : string,
  'bookingId' : string,
  'patientId' : string,
  'createdAt' : bigint,
  'collectedAt' : [] | [bigint],
  'updatedAt' : bigint,
  'totalAmount' : number,
  'testIds' : Array<string>,
  'sampleId' : string,
}
export interface DashboardStats {
  'pendingBookings' : bigint,
  'totalTests' : bigint,
  'totalPatients' : bigint,
  'totalBookings' : bigint,
  'currentTime' : bigint,
  'totalRevenue' : number,
  'monthlyRevenue' : number,
}
export interface LabSettings {
  'labEmail' : string,
  'reportFooter' : string,
  'reportHeader' : string,
  'labAddress' : string,
  'labPhone' : string,
  'currency' : string,
  'labName' : string,
}
export interface LabTest {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'parameters' : Array<TestParameter>,
  'updatedAt' : bigint,
  'category' : string,
  'price' : number,
}
export interface OutsourceLab {
  'id' : string,
  'assignedTests' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'contactPerson' : string,
  'email' : string,
  'updatedAt' : bigint,
  'address' : string,
  'phone' : string,
}
export interface Patient {
  'id' : string,
  'age' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'address' : string,
  'gender' : string,
  'phone' : string,
}
export interface Payment {
  'id' : string,
  'status' : string,
  'method' : string,
  'bookingId' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'partialAmount' : number,
  'amount' : number,
  'paidAt' : [] | [bigint],
}
export interface Report {
  'id' : string,
  'status' : string,
  'bookingId' : string,
  'approvedAt' : [] | [bigint],
  'approvedBy' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export interface TestParameter {
  'id' : string,
  'referenceMax' : [] | [number],
  'referenceMin' : [] | [number],
  'name' : string,
  'unit' : string,
  'referenceRange' : string,
}
export interface TestResult {
  'id' : string,
  'bookingId' : string,
  'value' : string,
  'isAbnormal' : boolean,
  'createdAt' : bigint,
  'unit' : string,
  'updatedAt' : bigint,
  'referenceRange' : string,
  'testId' : string,
  'parameterId' : string,
}
export interface _SERVICE {
  'approveReport' : ActorMethod<[string, string], undefined>,
  'approveTestResult' : ActorMethod<[string, string], undefined>,
  'createBooking' : ActorMethod<[Booking], undefined>,
  'createLabTest' : ActorMethod<[LabTest], undefined>,
  'createOutsourceLab' : ActorMethod<[OutsourceLab], undefined>,
  'createPatient' : ActorMethod<[Patient], undefined>,
  'createPayment' : ActorMethod<[Payment], undefined>,
  'createReport' : ActorMethod<[Report], undefined>,
  'createTestParameter' : ActorMethod<[TestParameter], undefined>,
  'createTestResult' : ActorMethod<[TestResult], undefined>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deleteLabTest' : ActorMethod<[string], undefined>,
  'deleteOutsourceLab' : ActorMethod<[string], undefined>,
  'deletePatient' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[string], undefined>,
  'deleteReport' : ActorMethod<[string], undefined>,
  'deleteTestParameter' : ActorMethod<[string], undefined>,
  'deleteTestResult' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllLabTests' : ActorMethod<[], Array<LabTest>>,
  'getAllOutsourceLabs' : ActorMethod<[], Array<OutsourceLab>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllTestParameters' : ActorMethod<[], Array<TestParameter>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getBookingsByPatient' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByStatus' : ActorMethod<[string], Array<Booking>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getLabTest' : ActorMethod<[string], LabTest>,
  'getOutsourceLab' : ActorMethod<[string], OutsourceLab>,
  'getPatient' : ActorMethod<[string], Patient>,
  'getPayment' : ActorMethod<[string], Payment>,
  'getPaymentByBooking' : ActorMethod<[string], [] | [Payment]>,
  'getReport' : ActorMethod<[string], Report>,
  'getReportByBooking' : ActorMethod<[string], [] | [Report]>,
  'getResultsByBooking' : ActorMethod<[string], Array<TestResult>>,
  'getSettings' : ActorMethod<[], [] | [LabSettings]>,
  'getTestParameter' : ActorMethod<[string], TestParameter>,
  'getTestResult' : ActorMethod<[string], TestResult>,
  'markPartialPayment' : ActorMethod<[string, number], undefined>,
  'markPaymentPaid' : ActorMethod<[string, string], undefined>,
  'markReportDelivered' : ActorMethod<[string], undefined>,
  'markSamplesCollected' : ActorMethod<[Array<string>], undefined>,
  'saveSettings' : ActorMethod<[LabSettings], undefined>,
  'searchPatients' : ActorMethod<[string], Array<Patient>>,
  'updateBooking' : ActorMethod<[Booking], undefined>,
  'updateLabTest' : ActorMethod<[LabTest], undefined>,
  'updateOutsourceLab' : ActorMethod<[OutsourceLab], undefined>,
  'updatePatient' : ActorMethod<[Patient], undefined>,
  'updatePayment' : ActorMethod<[Payment], undefined>,
  'updateReport' : ActorMethod<[Report], undefined>,
  'updateTestParameter' : ActorMethod<[TestParameter], undefined>,
  'updateTestResult' : ActorMethod<[TestResult], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];