/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OutsourceLab {
    id: string;
    assignedTests: Array<string>;
    name: string;
    createdAt: bigint;
    contactPerson: string;
    email: string;
    updatedAt: bigint;
    address: string;
    phone: string;
}
export interface TestResult {
    id: string;
    bookingId: string;
    value: string;
    isAbnormal: boolean;
    createdAt: bigint;
    unit: string;
    updatedAt: bigint;
    referenceRange: string;
    testId: string;
    parameterId: string;
}
export interface LabSettings {
    labEmail: string;
    reportFooter: string;
    reportHeader: string;
    labAddress: string;
    labPhone: string;
    currency: string;
    labName: string;
}
export interface DashboardStats {
    pendingBookings: bigint;
    totalTests: bigint;
    totalPatients: bigint;
    totalBookings: bigint;
    currentTime: bigint;
    totalRevenue: number;
    monthlyRevenue: number;
}
export interface Booking {
    id: string;
    status: string;
    bookingId: string;
    patientId: string;
    createdAt: bigint;
    collectedAt?: bigint;
    updatedAt: bigint;
    totalAmount: number;
    testIds: Array<string>;
    sampleId: string;
}
export interface TestParameter {
    id: string;
    referenceMax?: number;
    referenceMin?: number;
    name: string;
    unit: string;
    referenceRange: string;
}
export interface LabTest {
    id: string;
    name: string;
    createdAt: bigint;
    parameters: Array<TestParameter>;
    updatedAt: bigint;
    category: string;
    price: number;
}
export interface Report {
    id: string;
    status: string;
    bookingId: string;
    approvedAt?: bigint;
    approvedBy: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface Payment {
    id: string;
    status: string;
    method: string;
    bookingId: string;
    createdAt: bigint;
    updatedAt: bigint;
    partialAmount: number;
    amount: number;
    paidAt?: bigint;
}
export interface Patient {
    id: string;
    age: bigint;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    address: string;
    gender: string;
    phone: string;
}
export interface backendInterface {
    approveReport(reportId: string, approvedBy: string): Promise<void>;
    approveTestResult(resultId: string, approvedBy: string): Promise<void>;
    createBooking(booking: Booking): Promise<void>;
    createLabTest(test: LabTest): Promise<void>;
    createOutsourceLab(lab: OutsourceLab): Promise<void>;
    createPatient(patient: Patient): Promise<void>;
    createPayment(payment: Payment): Promise<void>;
    createReport(report: Report): Promise<void>;
    createTestParameter(param: TestParameter): Promise<void>;
    createTestResult(result: TestResult): Promise<void>;
    deleteBooking(id: string): Promise<void>;
    deleteLabTest(id: string): Promise<void>;
    deleteOutsourceLab(id: string): Promise<void>;
    deletePatient(id: string): Promise<void>;
    deletePayment(id: string): Promise<void>;
    deleteReport(id: string): Promise<void>;
    deleteTestParameter(id: string): Promise<void>;
    deleteTestResult(id: string): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllLabTests(): Promise<Array<LabTest>>;
    getAllOutsourceLabs(): Promise<Array<OutsourceLab>>;
    getAllPatients(): Promise<Array<Patient>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllTestParameters(): Promise<Array<TestParameter>>;
    getBooking(id: string): Promise<Booking>;
    getBookingsByPatient(patientId: string): Promise<Array<Booking>>;
    getBookingsByStatus(status: string): Promise<Array<Booking>>;
    getDashboardStats(): Promise<DashboardStats>;
    getLabTest(id: string): Promise<LabTest>;
    getOutsourceLab(id: string): Promise<OutsourceLab>;
    getPatient(id: string): Promise<Patient>;
    getPayment(id: string): Promise<Payment>;
    getPaymentByBooking(bookingId: string): Promise<Payment | null>;
    getReport(id: string): Promise<Report>;
    getReportByBooking(bookingId: string): Promise<Report | null>;
    getResultsByBooking(bookingId: string): Promise<Array<TestResult>>;
    getSettings(): Promise<LabSettings | null>;
    getTestParameter(id: string): Promise<TestParameter>;
    getTestResult(id: string): Promise<TestResult>;
    markPartialPayment(paymentId: string, amount: number): Promise<void>;
    markPaymentPaid(paymentId: string, method: string): Promise<void>;
    markReportDelivered(reportId: string): Promise<void>;
    markSamplesCollected(bookingIds: Array<string>): Promise<void>;
    saveSettings(settings: LabSettings): Promise<void>;
    searchPatients(searchQuery: string): Promise<Array<Patient>>;
    updateBooking(booking: Booking): Promise<void>;
    updateLabTest(test: LabTest): Promise<void>;
    updateOutsourceLab(lab: OutsourceLab): Promise<void>;
    updatePatient(patient: Patient): Promise<void>;
    updatePayment(payment: Payment): Promise<void>;
    updateReport(report: Report): Promise<void>;
    updateTestParameter(param: TestParameter): Promise<void>;
    updateTestResult(result: TestResult): Promise<void>;
}
import type { Booking as _Booking, LabSettings as _LabSettings, LabTest as _LabTest, Payment as _Payment, Report as _Report, TestParameter as _TestParameter } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveReport(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReport(arg0, arg1);
            return result;
        }
    }
    async approveTestResult(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTestResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTestResult(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_Booking_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_Booking_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createLabTest(arg0: LabTest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLabTest(to_candid_LabTest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLabTest(to_candid_LabTest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOutsourceLab(arg0: OutsourceLab): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOutsourceLab(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOutsourceLab(arg0);
            return result;
        }
    }
    async createPatient(arg0: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0);
            return result;
        }
    }
    async createPayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(to_candid_Payment_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(to_candid_Payment_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReport(arg0: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(to_candid_Report_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(to_candid_Report_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTestParameter(arg0: TestParameter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestParameter(to_candid_TestParameter_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestParameter(to_candid_TestParameter_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTestResult(arg0: TestResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestResult(arg0);
            return result;
        }
    }
    async deleteBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteLabTest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabTest(arg0);
            return result;
        }
    }
    async deleteOutsourceLab(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOutsourceLab(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOutsourceLab(arg0);
            return result;
        }
    }
    async deletePatient(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async deletePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async deleteReport(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async deleteTestParameter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestParameter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestParameter(arg0);
            return result;
        }
    }
    async deleteTestResult(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestResult(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLabTests(): Promise<Array<LabTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLabTests();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLabTests();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOutsourceLabs(): Promise<Array<OutsourceLab>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOutsourceLabs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOutsourceLabs();
            return result;
        }
    }
    async getAllPatients(): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestParameters(): Promise<Array<TestParameter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestParameters();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestParameters();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByPatient(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByPatient(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByPatient(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStatus(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getLabTest(arg0: string): Promise<LabTest> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabTest(arg0);
                return from_candid_LabTest_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabTest(arg0);
            return from_candid_LabTest_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOutsourceLab(arg0: string): Promise<OutsourceLab> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutsourceLab(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutsourceLab(arg0);
            return result;
        }
    }
    async getPatient(arg0: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return result;
        }
    }
    async getPayment(arg0: string): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_Payment_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_Payment_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentByBooking(arg0: string): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentByBooking(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentByBooking(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: string): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_Report_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_Report_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportByBooking(arg0: string): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportByBooking(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportByBooking(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResultsByBooking(arg0: string): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResultsByBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResultsByBooking(arg0);
            return result;
        }
    }
    async getSettings(): Promise<LabSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestParameter(arg0: string): Promise<TestParameter> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestParameter(arg0);
                return from_candid_TestParameter_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestParameter(arg0);
            return from_candid_TestParameter_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestResult(arg0: string): Promise<TestResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResult(arg0);
            return result;
        }
    }
    async markPartialPayment(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPartialPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPartialPayment(arg0, arg1);
            return result;
        }
    }
    async markPaymentPaid(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPaymentPaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPaymentPaid(arg0, arg1);
            return result;
        }
    }
    async markReportDelivered(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markReportDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markReportDelivered(arg0);
            return result;
        }
    }
    async markSamplesCollected(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSamplesCollected(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSamplesCollected(arg0);
            return result;
        }
    }
    async saveSettings(arg0: LabSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0);
            return result;
        }
    }
    async searchPatients(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatients(arg0);
            return result;
        }
    }
    async updateBooking(arg0: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(to_candid_Booking_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(to_candid_Booking_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLabTest(arg0: LabTest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLabTest(to_candid_LabTest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLabTest(to_candid_LabTest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOutsourceLab(arg0: OutsourceLab): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOutsourceLab(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOutsourceLab(arg0);
            return result;
        }
    }
    async updatePatient(arg0: Patient): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0);
            return result;
        }
    }
    async updatePayment(arg0: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(to_candid_Payment_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(to_candid_Payment_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateReport(arg0: Report): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(to_candid_Report_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(to_candid_Report_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTestParameter(arg0: TestParameter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestParameter(to_candid_TestParameter_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestParameter(to_candid_TestParameter_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTestResult(arg0: TestResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestResult(arg0);
            return result;
        }
    }
}
function from_candid_Booking_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_LabTest_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LabTest): LabTest {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TestParameter_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestParameter): TestParameter {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Report | null {
    return value.length === 0 ? null : from_candid_Report_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LabSettings]): LabSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    bookingId: string;
    patientId: string;
    createdAt: bigint;
    collectedAt: [] | [bigint];
    updatedAt: bigint;
    totalAmount: number;
    testIds: Array<string>;
    sampleId: string;
}): {
    id: string;
    status: string;
    bookingId: string;
    patientId: string;
    createdAt: bigint;
    collectedAt?: bigint;
    updatedAt: bigint;
    totalAmount: number;
    testIds: Array<string>;
    sampleId: string;
} {
    return {
        id: value.id,
        status: value.status,
        bookingId: value.bookingId,
        patientId: value.patientId,
        createdAt: value.createdAt,
        collectedAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.collectedAt)),
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        testIds: value.testIds,
        sampleId: value.sampleId
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    parameters: Array<_TestParameter>;
    updatedAt: bigint;
    category: string;
    price: number;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    parameters: Array<TestParameter>;
    updatedAt: bigint;
    category: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        parameters: from_candid_vec_n19(_uploadFile, _downloadFile, value.parameters),
        updatedAt: value.updatedAt,
        category: value.category,
        price: value.price
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referenceMax: [] | [number];
    referenceMin: [] | [number];
    name: string;
    unit: string;
    referenceRange: string;
}): {
    id: string;
    referenceMax?: number;
    referenceMin?: number;
    name: string;
    unit: string;
    referenceRange: string;
} {
    return {
        id: value.id,
        referenceMax: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.referenceMax)),
        referenceMin: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.referenceMin)),
        name: value.name,
        unit: value.unit,
        referenceRange: value.referenceRange
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    method: string;
    bookingId: string;
    createdAt: bigint;
    updatedAt: bigint;
    partialAmount: number;
    amount: number;
    paidAt: [] | [bigint];
}): {
    id: string;
    status: string;
    method: string;
    bookingId: string;
    createdAt: bigint;
    updatedAt: bigint;
    partialAmount: number;
    amount: number;
    paidAt?: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        method: value.method,
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        partialAmount: value.partialAmount,
        amount: value.amount,
        paidAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.paidAt))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    bookingId: string;
    approvedAt: [] | [bigint];
    approvedBy: string;
    createdAt: bigint;
    updatedAt: bigint;
}): {
    id: string;
    status: string;
    bookingId: string;
    approvedAt?: bigint;
    approvedBy: string;
    createdAt: bigint;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        bookingId: value.bookingId,
        approvedAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.approvedAt)),
        approvedBy: value.approvedBy,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LabTest>): Array<LabTest> {
    return value.map((x)=>from_candid_LabTest_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestParameter>): Array<TestParameter> {
    return value.map((x)=>from_candid_TestParameter_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n24(_uploadFile, _downloadFile, x));
}
function to_candid_Booking_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LabTest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LabTest): _LabTest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Report_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Report): _Report {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TestParameter_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestParameter): _TestParameter {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    bookingId: string;
    approvedAt?: bigint;
    approvedBy: string;
    createdAt: bigint;
    updatedAt: bigint;
}): {
    id: string;
    status: string;
    bookingId: string;
    approvedAt: [] | [bigint];
    approvedBy: string;
    createdAt: bigint;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        bookingId: value.bookingId,
        approvedAt: value.approvedAt ? candid_some(value.approvedAt) : candid_none(),
        approvedBy: value.approvedBy,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    bookingId: string;
    patientId: string;
    createdAt: bigint;
    collectedAt?: bigint;
    updatedAt: bigint;
    totalAmount: number;
    testIds: Array<string>;
    sampleId: string;
}): {
    id: string;
    status: string;
    bookingId: string;
    patientId: string;
    createdAt: bigint;
    collectedAt: [] | [bigint];
    updatedAt: bigint;
    totalAmount: number;
    testIds: Array<string>;
    sampleId: string;
} {
    return {
        id: value.id,
        status: value.status,
        bookingId: value.bookingId,
        patientId: value.patientId,
        createdAt: value.createdAt,
        collectedAt: value.collectedAt ? candid_some(value.collectedAt) : candid_none(),
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        testIds: value.testIds,
        sampleId: value.sampleId
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    parameters: Array<TestParameter>;
    updatedAt: bigint;
    category: string;
    price: number;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    parameters: Array<_TestParameter>;
    updatedAt: bigint;
    category: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        parameters: to_candid_vec_n5(_uploadFile, _downloadFile, value.parameters),
        updatedAt: value.updatedAt,
        category: value.category,
        price: value.price
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    referenceMax?: number;
    referenceMin?: number;
    name: string;
    unit: string;
    referenceRange: string;
}): {
    id: string;
    referenceMax: [] | [number];
    referenceMin: [] | [number];
    name: string;
    unit: string;
    referenceRange: string;
} {
    return {
        id: value.id,
        referenceMax: value.referenceMax ? candid_some(value.referenceMax) : candid_none(),
        referenceMin: value.referenceMin ? candid_some(value.referenceMin) : candid_none(),
        name: value.name,
        unit: value.unit,
        referenceRange: value.referenceRange
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    method: string;
    bookingId: string;
    createdAt: bigint;
    updatedAt: bigint;
    partialAmount: number;
    amount: number;
    paidAt?: bigint;
}): {
    id: string;
    status: string;
    method: string;
    bookingId: string;
    createdAt: bigint;
    updatedAt: bigint;
    partialAmount: number;
    amount: number;
    paidAt: [] | [bigint];
} {
    return {
        id: value.id,
        status: value.status,
        method: value.method,
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        partialAmount: value.partialAmount,
        amount: value.amount,
        paidAt: value.paidAt ? candid_some(value.paidAt) : candid_none()
    };
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TestParameter>): Array<_TestParameter> {
    return value.map((x)=>to_candid_TestParameter_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
